/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ide;

import org.xtext.de.htwg.ide.AbstractPhasesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PhasesIdeModule extends AbstractPhasesIdeModule {
}
