/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ide;

import com.google.inject.Injector;
import org.xtext.de.htwg.PhasesStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PhasesIdeSetup extends PhasesStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from PhasesIdeModule to Module");
  }
}
