/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(PhaseXPhasesInjectorProvider)
class PhaseXPhasesParsingTest {

	
	@Test
	def void loadModel() {

	}
}
