/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.de.htwg.ui.AbstractPhasesUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PhasesUiModule extends AbstractPhasesUiModule {
  public PhasesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
