/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PhasesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/de/htwg/parser/antlr/internal/InternalPhases.tokens");
	}
}
