/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.de.htwg.parser.antlr.internal.InternalPhasesParser;
import org.xtext.de.htwg.services.PhasesGrammarAccess;

public class PhasesParser extends AbstractAntlrParser {

	@Inject
	private PhasesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPhasesParser createParser(XtextTokenStream stream) {
		return new InternalPhasesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Game";
	}

	public PhasesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PhasesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
