/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg;

import org.xtext.de.htwg.AbstractPhasesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PhasesRuntimeModule extends AbstractPhasesRuntimeModule {
}
