/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg;

import org.xtext.de.htwg.PhasesStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PhasesStandaloneSetup extends PhasesStandaloneSetupGenerated {
  public static void doSetup() {
    PhasesStandaloneSetup _phasesStandaloneSetup = new PhasesStandaloneSetup();
    _phasesStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
