/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.validation;

import org.xtext.de.htwg.validation.AbstractPhasesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PhasesValidator extends AbstractPhasesValidator {
}
