/*
 * generated by Xtext 2.10.0
 */
package org.xtext.de.htwg.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPhasesScopeProvider extends DelegatingScopeProvider {
}
