/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.phases.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.de.htwg.phases.Game;
import org.xtext.de.htwg.phases.Phase;
import org.xtext.de.htwg.phases.PhasesPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Game</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.phases.impl.GameImpl#getPhase1 <em>Phase1</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.impl.GameImpl#getPhase2 <em>Phase2</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.impl.GameImpl#getPhase3 <em>Phase3</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.impl.GameImpl#getPhase4 <em>Phase4</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.impl.GameImpl#getPhase5 <em>Phase5</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GameImpl extends MinimalEObjectImpl.Container implements Game
{
  /**
   * The cached value of the '{@link #getPhase1() <em>Phase1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhase1()
   * @generated
   * @ordered
   */
  protected Phase phase1;

  /**
   * The cached value of the '{@link #getPhase2() <em>Phase2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhase2()
   * @generated
   * @ordered
   */
  protected Phase phase2;

  /**
   * The cached value of the '{@link #getPhase3() <em>Phase3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhase3()
   * @generated
   * @ordered
   */
  protected Phase phase3;

  /**
   * The cached value of the '{@link #getPhase4() <em>Phase4</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhase4()
   * @generated
   * @ordered
   */
  protected Phase phase4;

  /**
   * The cached value of the '{@link #getPhase5() <em>Phase5</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhase5()
   * @generated
   * @ordered
   */
  protected Phase phase5;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GameImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PhasesPackage.Literals.GAME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Phase getPhase1()
  {
    return phase1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPhase1(Phase newPhase1, NotificationChain msgs)
  {
    Phase oldPhase1 = phase1;
    phase1 = newPhase1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE1, oldPhase1, newPhase1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPhase1(Phase newPhase1)
  {
    if (newPhase1 != phase1)
    {
      NotificationChain msgs = null;
      if (phase1 != null)
        msgs = ((InternalEObject)phase1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE1, null, msgs);
      if (newPhase1 != null)
        msgs = ((InternalEObject)newPhase1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE1, null, msgs);
      msgs = basicSetPhase1(newPhase1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE1, newPhase1, newPhase1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Phase getPhase2()
  {
    return phase2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPhase2(Phase newPhase2, NotificationChain msgs)
  {
    Phase oldPhase2 = phase2;
    phase2 = newPhase2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE2, oldPhase2, newPhase2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPhase2(Phase newPhase2)
  {
    if (newPhase2 != phase2)
    {
      NotificationChain msgs = null;
      if (phase2 != null)
        msgs = ((InternalEObject)phase2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE2, null, msgs);
      if (newPhase2 != null)
        msgs = ((InternalEObject)newPhase2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE2, null, msgs);
      msgs = basicSetPhase2(newPhase2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE2, newPhase2, newPhase2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Phase getPhase3()
  {
    return phase3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPhase3(Phase newPhase3, NotificationChain msgs)
  {
    Phase oldPhase3 = phase3;
    phase3 = newPhase3;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE3, oldPhase3, newPhase3);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPhase3(Phase newPhase3)
  {
    if (newPhase3 != phase3)
    {
      NotificationChain msgs = null;
      if (phase3 != null)
        msgs = ((InternalEObject)phase3).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE3, null, msgs);
      if (newPhase3 != null)
        msgs = ((InternalEObject)newPhase3).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE3, null, msgs);
      msgs = basicSetPhase3(newPhase3, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE3, newPhase3, newPhase3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Phase getPhase4()
  {
    return phase4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPhase4(Phase newPhase4, NotificationChain msgs)
  {
    Phase oldPhase4 = phase4;
    phase4 = newPhase4;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE4, oldPhase4, newPhase4);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPhase4(Phase newPhase4)
  {
    if (newPhase4 != phase4)
    {
      NotificationChain msgs = null;
      if (phase4 != null)
        msgs = ((InternalEObject)phase4).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE4, null, msgs);
      if (newPhase4 != null)
        msgs = ((InternalEObject)newPhase4).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE4, null, msgs);
      msgs = basicSetPhase4(newPhase4, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE4, newPhase4, newPhase4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Phase getPhase5()
  {
    return phase5;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPhase5(Phase newPhase5, NotificationChain msgs)
  {
    Phase oldPhase5 = phase5;
    phase5 = newPhase5;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE5, oldPhase5, newPhase5);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPhase5(Phase newPhase5)
  {
    if (newPhase5 != phase5)
    {
      NotificationChain msgs = null;
      if (phase5 != null)
        msgs = ((InternalEObject)phase5).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE5, null, msgs);
      if (newPhase5 != null)
        msgs = ((InternalEObject)newPhase5).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PhasesPackage.GAME__PHASE5, null, msgs);
      msgs = basicSetPhase5(newPhase5, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PhasesPackage.GAME__PHASE5, newPhase5, newPhase5));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PhasesPackage.GAME__PHASE1:
        return basicSetPhase1(null, msgs);
      case PhasesPackage.GAME__PHASE2:
        return basicSetPhase2(null, msgs);
      case PhasesPackage.GAME__PHASE3:
        return basicSetPhase3(null, msgs);
      case PhasesPackage.GAME__PHASE4:
        return basicSetPhase4(null, msgs);
      case PhasesPackage.GAME__PHASE5:
        return basicSetPhase5(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PhasesPackage.GAME__PHASE1:
        return getPhase1();
      case PhasesPackage.GAME__PHASE2:
        return getPhase2();
      case PhasesPackage.GAME__PHASE3:
        return getPhase3();
      case PhasesPackage.GAME__PHASE4:
        return getPhase4();
      case PhasesPackage.GAME__PHASE5:
        return getPhase5();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PhasesPackage.GAME__PHASE1:
        setPhase1((Phase)newValue);
        return;
      case PhasesPackage.GAME__PHASE2:
        setPhase2((Phase)newValue);
        return;
      case PhasesPackage.GAME__PHASE3:
        setPhase3((Phase)newValue);
        return;
      case PhasesPackage.GAME__PHASE4:
        setPhase4((Phase)newValue);
        return;
      case PhasesPackage.GAME__PHASE5:
        setPhase5((Phase)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PhasesPackage.GAME__PHASE1:
        setPhase1((Phase)null);
        return;
      case PhasesPackage.GAME__PHASE2:
        setPhase2((Phase)null);
        return;
      case PhasesPackage.GAME__PHASE3:
        setPhase3((Phase)null);
        return;
      case PhasesPackage.GAME__PHASE4:
        setPhase4((Phase)null);
        return;
      case PhasesPackage.GAME__PHASE5:
        setPhase5((Phase)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PhasesPackage.GAME__PHASE1:
        return phase1 != null;
      case PhasesPackage.GAME__PHASE2:
        return phase2 != null;
      case PhasesPackage.GAME__PHASE3:
        return phase3 != null;
      case PhasesPackage.GAME__PHASE4:
        return phase4 != null;
      case PhasesPackage.GAME__PHASE5:
        return phase5 != null;
    }
    return super.eIsSet(featureID);
  }

} //GameImpl
