/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.phases.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.de.htwg.phases.NUMBERS_TYPE;
import org.xtext.de.htwg.phases.PhasesPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>NUMBERS TYPE</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.phases.impl.NUMBERS_TYPEImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.impl.NUMBERS_TYPEImpl#getNumbersType <em>Numbers Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NUMBERS_TYPEImpl extends MinimalEObjectImpl.Container implements NUMBERS_TYPE
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getNumbersType() <em>Numbers Type</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumbersType()
   * @generated
   * @ordered
   */
  protected EList<String> numbersType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NUMBERS_TYPEImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PhasesPackage.Literals.NUMBERS_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PhasesPackage.NUMBERS_TYPE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getNumbersType()
  {
    if (numbersType == null)
    {
      numbersType = new EDataTypeEList<String>(String.class, this, PhasesPackage.NUMBERS_TYPE__NUMBERS_TYPE);
    }
    return numbersType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PhasesPackage.NUMBERS_TYPE__NAME:
        return getName();
      case PhasesPackage.NUMBERS_TYPE__NUMBERS_TYPE:
        return getNumbersType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PhasesPackage.NUMBERS_TYPE__NAME:
        setName((String)newValue);
        return;
      case PhasesPackage.NUMBERS_TYPE__NUMBERS_TYPE:
        getNumbersType().clear();
        getNumbersType().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PhasesPackage.NUMBERS_TYPE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PhasesPackage.NUMBERS_TYPE__NUMBERS_TYPE:
        getNumbersType().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PhasesPackage.NUMBERS_TYPE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PhasesPackage.NUMBERS_TYPE__NUMBERS_TYPE:
        return numbersType != null && !numbersType.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", numbersType: ");
    result.append(numbersType);
    result.append(')');
    return result.toString();
  }

} //NUMBERS_TYPEImpl
