/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ui.contentassist;

import org.xtext.de.htwg.ui.contentassist.AbstractPhasesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PhasesProposalProvider extends AbstractPhasesProposalProvider {
}
