/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.phases;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>COLORS TYPE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.phases.COLORS_TYPE#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.COLORS_TYPE#getNumberColors <em>Number Colors</em>}</li>
 * </ul>
 *
 * @see org.xtext.de.htwg.phases.PhasesPackage#getCOLORS_TYPE()
 * @model
 * @generated
 */
public interface COLORS_TYPE extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.de.htwg.phases.PhasesPackage#getCOLORS_TYPE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.phases.COLORS_TYPE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Number Colors</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number Colors</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number Colors</em>' attribute.
   * @see #setNumberColors(int)
   * @see org.xtext.de.htwg.phases.PhasesPackage#getCOLORS_TYPE_NumberColors()
   * @model
   * @generated
   */
  int getNumberColors();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.phases.COLORS_TYPE#getNumberColors <em>Number Colors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number Colors</em>' attribute.
   * @see #getNumberColors()
   * @generated
   */
  void setNumberColors(int value);

} // COLORS_TYPE
