/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.phases;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NUMBERS TYPE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.phases.NUMBERS_TYPE#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.NUMBERS_TYPE#getNumbersType <em>Numbers Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.de.htwg.phases.PhasesPackage#getNUMBERS_TYPE()
 * @model
 * @generated
 */
public interface NUMBERS_TYPE extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.de.htwg.phases.PhasesPackage#getNUMBERS_TYPE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.phases.NUMBERS_TYPE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Numbers Type</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numbers Type</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numbers Type</em>' attribute list.
   * @see org.xtext.de.htwg.phases.PhasesPackage#getNUMBERS_TYPE_NumbersType()
   * @model unique="false"
   * @generated
   */
  EList<String> getNumbersType();

} // NUMBERS_TYPE
