/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.phases;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Phase Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.phases.PhaseType#getStreetType <em>Street Type</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.PhaseType#getNumbersType <em>Numbers Type</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.PhaseType#getColorType <em>Color Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.de.htwg.phases.PhasesPackage#getPhaseType()
 * @model
 * @generated
 */
public interface PhaseType extends EObject
{
  /**
   * Returns the value of the '<em><b>Street Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Street Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Street Type</em>' containment reference.
   * @see #setStreetType(STREET_TYPE)
   * @see org.xtext.de.htwg.phases.PhasesPackage#getPhaseType_StreetType()
   * @model containment="true"
   * @generated
   */
  STREET_TYPE getStreetType();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.phases.PhaseType#getStreetType <em>Street Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Street Type</em>' containment reference.
   * @see #getStreetType()
   * @generated
   */
  void setStreetType(STREET_TYPE value);

  /**
   * Returns the value of the '<em><b>Numbers Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numbers Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numbers Type</em>' containment reference.
   * @see #setNumbersType(NUMBERS_TYPE)
   * @see org.xtext.de.htwg.phases.PhasesPackage#getPhaseType_NumbersType()
   * @model containment="true"
   * @generated
   */
  NUMBERS_TYPE getNumbersType();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.phases.PhaseType#getNumbersType <em>Numbers Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Numbers Type</em>' containment reference.
   * @see #getNumbersType()
   * @generated
   */
  void setNumbersType(NUMBERS_TYPE value);

  /**
   * Returns the value of the '<em><b>Color Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color Type</em>' containment reference.
   * @see #setColorType(COLORS_TYPE)
   * @see org.xtext.de.htwg.phases.PhasesPackage#getPhaseType_ColorType()
   * @model containment="true"
   * @generated
   */
  COLORS_TYPE getColorType();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.phases.PhaseType#getColorType <em>Color Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color Type</em>' containment reference.
   * @see #getColorType()
   * @generated
   */
  void setColorType(COLORS_TYPE value);

} // PhaseType
