/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.phases;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.de.htwg.phases.PhasesFactory
 * @model kind="package"
 * @generated
 */
public interface PhasesPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "phases";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/de/htwg/Phases";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "phases";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PhasesPackage eINSTANCE = org.xtext.de.htwg.phases.impl.PhasesPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.de.htwg.phases.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.de.htwg.phases.impl.GameImpl
   * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Phase1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__PHASE1 = 0;

  /**
   * The feature id for the '<em><b>Phase2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__PHASE2 = 1;

  /**
   * The feature id for the '<em><b>Phase3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__PHASE3 = 2;

  /**
   * The feature id for the '<em><b>Phase4</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__PHASE4 = 3;

  /**
   * The feature id for the '<em><b>Phase5</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__PHASE5 = 4;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.de.htwg.phases.impl.PhaseImpl <em>Phase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.de.htwg.phases.impl.PhaseImpl
   * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getPhase()
   * @generated
   */
  int PHASE = 1;

  /**
   * The feature id for the '<em><b>Phase Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE__PHASE_NUMBER = 0;

  /**
   * The feature id for the '<em><b>Phase Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE__PHASE_TYPE = 1;

  /**
   * The number of structural features of the '<em>Phase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.de.htwg.phases.impl.PhaseTypeImpl <em>Phase Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.de.htwg.phases.impl.PhaseTypeImpl
   * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getPhaseType()
   * @generated
   */
  int PHASE_TYPE = 2;

  /**
   * The feature id for the '<em><b>Street Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE_TYPE__STREET_TYPE = 0;

  /**
   * The feature id for the '<em><b>Numbers Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE_TYPE__NUMBERS_TYPE = 1;

  /**
   * The feature id for the '<em><b>Color Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE_TYPE__COLOR_TYPE = 2;

  /**
   * The number of structural features of the '<em>Phase Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.de.htwg.phases.impl.NUMBERS_TYPEImpl <em>NUMBERS TYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.de.htwg.phases.impl.NUMBERS_TYPEImpl
   * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getNUMBERS_TYPE()
   * @generated
   */
  int NUMBERS_TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERS_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Numbers Type</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERS_TYPE__NUMBERS_TYPE = 1;

  /**
   * The number of structural features of the '<em>NUMBERS TYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERS_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.de.htwg.phases.impl.COLORS_TYPEImpl <em>COLORS TYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.de.htwg.phases.impl.COLORS_TYPEImpl
   * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getCOLORS_TYPE()
   * @generated
   */
  int COLORS_TYPE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLORS_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Number Colors</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLORS_TYPE__NUMBER_COLORS = 1;

  /**
   * The number of structural features of the '<em>COLORS TYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLORS_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.de.htwg.phases.impl.STREET_TYPEImpl <em>STREET TYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.de.htwg.phases.impl.STREET_TYPEImpl
   * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getSTREET_TYPE()
   * @generated
   */
  int STREET_TYPE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREET_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Street Lenght</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREET_TYPE__STREET_LENGHT = 1;

  /**
   * The number of structural features of the '<em>STREET TYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREET_TYPE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.de.htwg.phases.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see org.xtext.de.htwg.phases.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.Game#getPhase1 <em>Phase1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Phase1</em>'.
   * @see org.xtext.de.htwg.phases.Game#getPhase1()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Phase1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.Game#getPhase2 <em>Phase2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Phase2</em>'.
   * @see org.xtext.de.htwg.phases.Game#getPhase2()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Phase2();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.Game#getPhase3 <em>Phase3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Phase3</em>'.
   * @see org.xtext.de.htwg.phases.Game#getPhase3()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Phase3();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.Game#getPhase4 <em>Phase4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Phase4</em>'.
   * @see org.xtext.de.htwg.phases.Game#getPhase4()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Phase4();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.Game#getPhase5 <em>Phase5</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Phase5</em>'.
   * @see org.xtext.de.htwg.phases.Game#getPhase5()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Phase5();

  /**
   * Returns the meta object for class '{@link org.xtext.de.htwg.phases.Phase <em>Phase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Phase</em>'.
   * @see org.xtext.de.htwg.phases.Phase
   * @generated
   */
  EClass getPhase();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.de.htwg.phases.Phase#getPhaseNumber <em>Phase Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phase Number</em>'.
   * @see org.xtext.de.htwg.phases.Phase#getPhaseNumber()
   * @see #getPhase()
   * @generated
   */
  EAttribute getPhase_PhaseNumber();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.Phase#getPhaseType <em>Phase Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Phase Type</em>'.
   * @see org.xtext.de.htwg.phases.Phase#getPhaseType()
   * @see #getPhase()
   * @generated
   */
  EReference getPhase_PhaseType();

  /**
   * Returns the meta object for class '{@link org.xtext.de.htwg.phases.PhaseType <em>Phase Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Phase Type</em>'.
   * @see org.xtext.de.htwg.phases.PhaseType
   * @generated
   */
  EClass getPhaseType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.PhaseType#getStreetType <em>Street Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Street Type</em>'.
   * @see org.xtext.de.htwg.phases.PhaseType#getStreetType()
   * @see #getPhaseType()
   * @generated
   */
  EReference getPhaseType_StreetType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.PhaseType#getNumbersType <em>Numbers Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Numbers Type</em>'.
   * @see org.xtext.de.htwg.phases.PhaseType#getNumbersType()
   * @see #getPhaseType()
   * @generated
   */
  EReference getPhaseType_NumbersType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.phases.PhaseType#getColorType <em>Color Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Color Type</em>'.
   * @see org.xtext.de.htwg.phases.PhaseType#getColorType()
   * @see #getPhaseType()
   * @generated
   */
  EReference getPhaseType_ColorType();

  /**
   * Returns the meta object for class '{@link org.xtext.de.htwg.phases.NUMBERS_TYPE <em>NUMBERS TYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>NUMBERS TYPE</em>'.
   * @see org.xtext.de.htwg.phases.NUMBERS_TYPE
   * @generated
   */
  EClass getNUMBERS_TYPE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.de.htwg.phases.NUMBERS_TYPE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.de.htwg.phases.NUMBERS_TYPE#getName()
   * @see #getNUMBERS_TYPE()
   * @generated
   */
  EAttribute getNUMBERS_TYPE_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.de.htwg.phases.NUMBERS_TYPE#getNumbersType <em>Numbers Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Numbers Type</em>'.
   * @see org.xtext.de.htwg.phases.NUMBERS_TYPE#getNumbersType()
   * @see #getNUMBERS_TYPE()
   * @generated
   */
  EAttribute getNUMBERS_TYPE_NumbersType();

  /**
   * Returns the meta object for class '{@link org.xtext.de.htwg.phases.COLORS_TYPE <em>COLORS TYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>COLORS TYPE</em>'.
   * @see org.xtext.de.htwg.phases.COLORS_TYPE
   * @generated
   */
  EClass getCOLORS_TYPE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.de.htwg.phases.COLORS_TYPE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.de.htwg.phases.COLORS_TYPE#getName()
   * @see #getCOLORS_TYPE()
   * @generated
   */
  EAttribute getCOLORS_TYPE_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.de.htwg.phases.COLORS_TYPE#getNumberColors <em>Number Colors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number Colors</em>'.
   * @see org.xtext.de.htwg.phases.COLORS_TYPE#getNumberColors()
   * @see #getCOLORS_TYPE()
   * @generated
   */
  EAttribute getCOLORS_TYPE_NumberColors();

  /**
   * Returns the meta object for class '{@link org.xtext.de.htwg.phases.STREET_TYPE <em>STREET TYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>STREET TYPE</em>'.
   * @see org.xtext.de.htwg.phases.STREET_TYPE
   * @generated
   */
  EClass getSTREET_TYPE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.de.htwg.phases.STREET_TYPE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.de.htwg.phases.STREET_TYPE#getName()
   * @see #getSTREET_TYPE()
   * @generated
   */
  EAttribute getSTREET_TYPE_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.de.htwg.phases.STREET_TYPE#getStreetLenght <em>Street Lenght</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Street Lenght</em>'.
   * @see org.xtext.de.htwg.phases.STREET_TYPE#getStreetLenght()
   * @see #getSTREET_TYPE()
   * @generated
   */
  EAttribute getSTREET_TYPE_StreetLenght();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PhasesFactory getPhasesFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.de.htwg.phases.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.de.htwg.phases.impl.GameImpl
     * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Phase1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__PHASE1 = eINSTANCE.getGame_Phase1();

    /**
     * The meta object literal for the '<em><b>Phase2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__PHASE2 = eINSTANCE.getGame_Phase2();

    /**
     * The meta object literal for the '<em><b>Phase3</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__PHASE3 = eINSTANCE.getGame_Phase3();

    /**
     * The meta object literal for the '<em><b>Phase4</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__PHASE4 = eINSTANCE.getGame_Phase4();

    /**
     * The meta object literal for the '<em><b>Phase5</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__PHASE5 = eINSTANCE.getGame_Phase5();

    /**
     * The meta object literal for the '{@link org.xtext.de.htwg.phases.impl.PhaseImpl <em>Phase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.de.htwg.phases.impl.PhaseImpl
     * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getPhase()
     * @generated
     */
    EClass PHASE = eINSTANCE.getPhase();

    /**
     * The meta object literal for the '<em><b>Phase Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PHASE__PHASE_NUMBER = eINSTANCE.getPhase_PhaseNumber();

    /**
     * The meta object literal for the '<em><b>Phase Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASE__PHASE_TYPE = eINSTANCE.getPhase_PhaseType();

    /**
     * The meta object literal for the '{@link org.xtext.de.htwg.phases.impl.PhaseTypeImpl <em>Phase Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.de.htwg.phases.impl.PhaseTypeImpl
     * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getPhaseType()
     * @generated
     */
    EClass PHASE_TYPE = eINSTANCE.getPhaseType();

    /**
     * The meta object literal for the '<em><b>Street Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASE_TYPE__STREET_TYPE = eINSTANCE.getPhaseType_StreetType();

    /**
     * The meta object literal for the '<em><b>Numbers Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASE_TYPE__NUMBERS_TYPE = eINSTANCE.getPhaseType_NumbersType();

    /**
     * The meta object literal for the '<em><b>Color Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASE_TYPE__COLOR_TYPE = eINSTANCE.getPhaseType_ColorType();

    /**
     * The meta object literal for the '{@link org.xtext.de.htwg.phases.impl.NUMBERS_TYPEImpl <em>NUMBERS TYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.de.htwg.phases.impl.NUMBERS_TYPEImpl
     * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getNUMBERS_TYPE()
     * @generated
     */
    EClass NUMBERS_TYPE = eINSTANCE.getNUMBERS_TYPE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBERS_TYPE__NAME = eINSTANCE.getNUMBERS_TYPE_Name();

    /**
     * The meta object literal for the '<em><b>Numbers Type</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBERS_TYPE__NUMBERS_TYPE = eINSTANCE.getNUMBERS_TYPE_NumbersType();

    /**
     * The meta object literal for the '{@link org.xtext.de.htwg.phases.impl.COLORS_TYPEImpl <em>COLORS TYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.de.htwg.phases.impl.COLORS_TYPEImpl
     * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getCOLORS_TYPE()
     * @generated
     */
    EClass COLORS_TYPE = eINSTANCE.getCOLORS_TYPE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLORS_TYPE__NAME = eINSTANCE.getCOLORS_TYPE_Name();

    /**
     * The meta object literal for the '<em><b>Number Colors</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLORS_TYPE__NUMBER_COLORS = eINSTANCE.getCOLORS_TYPE_NumberColors();

    /**
     * The meta object literal for the '{@link org.xtext.de.htwg.phases.impl.STREET_TYPEImpl <em>STREET TYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.de.htwg.phases.impl.STREET_TYPEImpl
     * @see org.xtext.de.htwg.phases.impl.PhasesPackageImpl#getSTREET_TYPE()
     * @generated
     */
    EClass STREET_TYPE = eINSTANCE.getSTREET_TYPE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STREET_TYPE__NAME = eINSTANCE.getSTREET_TYPE_Name();

    /**
     * The meta object literal for the '<em><b>Street Lenght</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STREET_TYPE__STREET_LENGHT = eINSTANCE.getSTREET_TYPE_StreetLenght();

  }

} //PhasesPackage
