/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.phases;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Phase</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.de.htwg.phases.PhasesPackage#getPhase()
 * @model
 * @generated
 */
public interface Phase extends EObject
{
} // Phase
