/**
 * generated by Xtext 2.10.0
 */
package org.xtext.de.htwg.phases;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>STREET TYPE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.phases.STREET_TYPE#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.de.htwg.phases.STREET_TYPE#getStreetLenght <em>Street Lenght</em>}</li>
 * </ul>
 *
 * @see org.xtext.de.htwg.phases.PhasesPackage#getSTREET_TYPE()
 * @model
 * @generated
 */
public interface STREET_TYPE extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.de.htwg.phases.PhasesPackage#getSTREET_TYPE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.phases.STREET_TYPE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Street Lenght</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Street Lenght</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Street Lenght</em>' attribute.
   * @see #setStreetLenght(int)
   * @see org.xtext.de.htwg.phases.PhasesPackage#getSTREET_TYPE_StreetLenght()
   * @model
   * @generated
   */
  int getStreetLenght();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.phases.STREET_TYPE#getStreetLenght <em>Street Lenght</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Street Lenght</em>' attribute.
   * @see #getStreetLenght()
   * @generated
   */
  void setStreetLenght(int value);

} // STREET_TYPE
