/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.tests;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.de.htwg.phases.Game;
import org.xtext.de.htwg.tests.PhasesInjectorProvider;

/* @RunWith(/* name is null */)
@InjectWith(PhasesInjectorProvider.class) */@SuppressWarnings("all")
public class PhasesParsingTest {
  /* @Inject
   */private /* ParseHelper<Game> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field PhasesParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
